#------------------------------
# Test GitHub Actions + Ansible
# Sergii Kiskar August 2022, Kyiv
# 
# 
#-----------------------------
name: repository-push-control
on: 
  push:
    branches: [ "main" ]
    paths-ignore:
      - "Ansible/**"
      - ".github/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          # optional output format
          # output: 'csv'
          # optional fileoutput format
          fileOutput: 'csv'
          
      - name: Detect # Detect modified and added files in the repository
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          # echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          # echo '${{ steps.file_changes.outputs.files_added}}'
         
      
      - name: Starting Playbook
        env:
          ext: "Ext of file of configuration"
          req_name: "Name of file requirements"
          req_name_config:  "Name of file configuration"
        run: |
         echo "Starting Ansible...."
         cd $GITHUB_WORKSPACE/Ansible
         ansible-playbook ansible_test_playbook.yml --extra-vars "ans_path=$GITHUB_WORKSPACE"
      
      
      
      
  #    - name: Starting Playbook
  #      env:
  #        ext: "Ext of file of configuration"
  #        req_name: "Name of file requirements"
  #        req_name_config:  "Name of file configuration"
  #        # trim '"' and '[', ']' signs            
  #      run: |
  #        sed -e 's/\[//; s/\"//g; s/\]//g' $HOME/files_modified.json > $HOME/file_install_req_mod.json
  #        Field_Separator=$IFS
  #        IFS=,
  #        # loop through json get file basename, ext and config name
  #        for val in $(cat $HOME/file_install_req_mod.json);
  #        do
  #        req_name_config=$(basename $val)
  #        echo "Running the configuration file - $req_name_config"
  #        req_name=${req_name_config%.*}
  #        ext=${req_name_config##*.}
  #        # if file is .txt start ansible          
  #        if [ "$ext" == "txt" ]
  #        then
  #        echo "Starting Ansible...."
  #        cd $GITHUB_WORKSPACE/Ansible
  #        ansible-playbook ansible_test_playbook.yml --extra-vars "ans_name_conf=$req_name ans_path=$GITHUB_WORKSPACE"
  #        else
  #        echo "This is not configuration file"
  #        fi
  #        done
  #        IFS=$Field_Separator        
